In [ ]:
!ls

oprm_project_domain_dataset.csv  sample_data

In [ ]:
!pip install nltk scikit-learn pandas

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

print('all imported')

all imported

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
df = pd.read_csv("oprm_project_domain_dataset.csv")

df.head()

   id                                       project_idea            domain
0   1  implement a recommendation system for smart ho...  Machine Learning
1   2  build a machine learning model to predict smar...  Machine Learning
2   3  develop a regression model for news articles p...  Machine Learning
3   4  develop a regression model for agriculture mon...  Machine Learning
4   5  implement a recommendation system for vehicle ...  Machine Learning

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1440 non-null   int64
 1   project_idea  1440 non-null   object
 2   domain        1440 non-null   object
dtypes: int64(1), object(2)
memory usage: 33.9+ KB

In [ ]:
df['domain'].value_counts()

domain
Machine Learning               120
Data Science                   120
Web Development                120
Mobile Development             120
Natural Language Processing    120
Computer Vision                120
Cloud Computing                120
Cybersecurity                  120
Internet of Things             120
Blockchain                     120
Database Systems               120
Software Engineering           120
Name: count, dtype: int64

In [ ]:
stop_words = set(stopwords.words('english'))

def preprocess(text):

    text = text.lower()

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word.isalpha()]

    tokens = [word for word in tokens if word not in stop_words]

    return " ".join(tokens)

In [ ]:
df['clean_text'] = df['project_idea'].apply(preprocess)

df.head()

,id,project_idea,domain,clean_text
0,1,implement a recommendation system for smart ho...,Machine Learning,implement recommendation system smart home dev...
1,2,build a machine learning model to predict smar...,Machine Learning,build machine learning model predict smart hom...
2,3,develop a regression model for news articles p...,Machine Learning,develop regression model news articles prediction
3,4,develop a regression model for agriculture mon...,Machine Learning,develop regression model agriculture monitorin...
4,5,implement a recommendation system for vehicle ...,Machine Learning,implement recommendation system vehicle tracki...

In [ ]:
X = df['clean_text']
y = df['domain']
print(X,y)

0       implement recommendation system smart home dev...
1       build machine learning model predict smart hom...
2       develop regression model news articles prediction
3       develop regression model agriculture monitorin...
4       implement recommendation system vehicle tracki...
                              ...
1435    build automated testing platform job portals s...
1436    develop continuous integration system student ...
1437    design modular architecture news articles appl...
1438    build automated testing platform news articles...
1439    build automated testing platform banking trans...
Name: clean_text, Length: 1440, dtype: object 0           Machine Learning
1           Machine Learning
2           Machine Learning
3           Machine Learning
4           Machine Learning
                ...
1435    Software Engineering
1436    Software Engineering
1437    Software Engineering
1438    Software Engineering
1439    Software Engineering
Name: domain, Length: 1440, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)

X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
model = LogisticRegression(max_iter=200)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=200)

In [ ]:
y_pred = model.predict(X_test_tfidf)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [ ]:
print(classification_report(y_test, y_pred))

                             precision    recall  f1-score   support

                 Blockchain       1.00      1.00      1.00        23
            Cloud Computing       1.00      1.00      1.00        25
            Computer Vision       1.00      1.00      1.00        26
              Cybersecurity       1.00      1.00      1.00        27
               Data Science       1.00      1.00      1.00        18
           Database Systems       1.00      1.00      1.00        21
         Internet of Things       1.00      1.00      1.00        22
           Machine Learning       1.00      1.00      1.00        24
         Mobile Development       1.00      1.00      1.00        23
Natural Language Processing       1.00      1.00      1.00        26
       Software Engineering       1.00      1.00      1.00        27
            Web Development       1.00      1.00      1.00        26

                   accuracy                           1.00       288
                  macro avg       1.00      1.00      1.00       288
               weighted avg       1.00      1.00      1.00       288

In [ ]:
def predict_domains(text, top_n=3):

    clean = preprocess(text)

    vector = vectorizer.transform([clean])

    probs = model.predict_proba(vector)

    classes = model.classes_

    probs = probs[0]

    top_indices = probs.argsort()[-top_n:][::-1]

    results = [(classes[i], probs[i]) for i in top_indices]

    return results

In [ ]:
idea = "Android app for food delivery"

predict_domains(idea, top_n=5)

[('Mobile Development', np.float64(0.8094970896327068)),
 ('Machine Learning', np.float64(0.020558254761982662)),
 ('Natural Language Processing', np.float64(0.02016756090651149)),
 ('Cloud Computing', np.float64(0.017726957855246177)),
 ('Computer Vision', np.float64(0.017576107555049902))]

In [ ]:
import joblib

In [ ]:
joblib.dump(model, "domain_classifier.pkl")

joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [ ]:
from google.colab import files

In [ ]:
files.download("domain_classifier.pkl")
files.download("tfidf_vectorizer.pkl")

In [ ]:
!ls

domain_classifier.pkl		 sample_data
oprm_project_domain_dataset.csv  tfidf_vectorizer.pkl

In [ ]:
predict_domains("IoT smart home automation system", top_n=3)

[('Internet of Things', np.float64(0.9398020214511803)),
 ('Blockchain', np.float64(0.009479648549493108)),
 ('Natural Language Processing', np.float64(0.006578215821131538))]